language: node_js
node_js:
- "8"
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - npm run cover
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=diegotkd94 -Dsonar.projectKey=DiegoTKD94_micalc -Dsonar.sources='./app' -X